# Generated by Django 2.0.3 on 2018-03-08 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import members.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='physical address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateTimeField(blank=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='change_date',
            field=models.DateTimeField(blank=True, verbose_name='date of last status update'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=enumfields.fields.EnumField(blank=True, enum=members.models.Gender, max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateTimeField(blank=True, verbose_name='date joined'),
        ),
    ]
